m2kcli/examples: added m2k_tty.sh script
analogdevicesinc/libm2k pull request #323
Opened 2022-09-12 08:49 UTC by bindea-cristian

The script connects the UART-Terminal to a PTY in order to communicate with a device using a Serial Terminal Emulator.

It uses the socat command to create two connected PTYs (pseudoterminal interfaces) and using the m2kcli uart-terminal command makes the connection between a PTY and our UART-Terminal.
The user can connect to the other PTY using a serial port terminal emulator (like GTKTerm, Picocom, Minicom, Tera Term).

More details [here](https://wiki.analog.com/university/tools/m2k/libm2k/m2kcli#usb_to_serial_uart_adapter_script).

Signed-off-by: Cristian Bindea <cristian.bindea@analog.com>

2022-09-13 12:32 UTC, adisuciu approved these changes

2022-09-14 08:35 UTC, AlexandraTrifan requested changes

2022-09-14 08:35 UTC, AlexandraTrifan commented on tools/m2kcli/examples/m2k_tty.sh
> +m2kcli uart-terminal "${uri}" -i baud_rate="${baud_rate}" rx="${rx}" tx="${tx}" stop_bits="${stop_bits}" parity="${parity}" bits_number="${bits_number}" <"${path[0]}" | tee -a "${temp_file}" >"${path
I think we should check whether the selected uri (or the default on) actually points to a device. If no M2K is connected, then we should catch the error and stop the script.

2022-09-19 07:51 UTC, AlexandraTrifan approved these changes

2022-09-19 07:51 UTC, merged