ContextBuilder: solve context close bug using reference count
analogdevicesinc/libm2k pull request #344
Opened 2023-09-27 09:45 UTC by Adrian-Stanea

- added reference count to ContextBuilder to keep track of how many external references to the M2k context are present. When the last reference is removed, the M2k context can be closed.
- contexts should be closed in the reverse order they were opened: contextClose() -> iio_context_destroy() to avoid pointer errors.
- based on context ownership, the user of the API is responsible of deinitalizing resources.

2023-10-02 11:03 UTC, AlexandraTrifan approved these changes

2023-10-02 13:39 UTC, adisuciu requested changes

2023-10-02 13:39 UTC, adisuciu commented on include/libm2k/contextbuilder.hpp
> +	static Context* sarchInConnectedDevices(std::string uri);
typo: searchInConnectedDevices

2023-10-02 13:39 UTC, adisuciu commented on src/contextbuilder.cpp
> +			updateReferenceCount(uri);
Your search function also updates the reference count .. Is this correct ?

2023-10-02 13:39 UTC, adisuciu commented on src/contextbuilder.cpp
> +	if(reference_count.find(uri) == reference_count.end()) {
Try to be explicit if possible (reference_count.count() == 0)

2023-10-02 13:39 UTC, adisuciu commented on src/contextbuilder.cpp
> +	if(isDeviceCached) {
Can you should use the search function here

2023-10-02 13:39 UTC, adisuciu commented on src/contextbuilder.cpp
> +		reference_count[uri]--;
You have a function to increment, but you don't have one for decrement. Maybe review this

2023-10-02 13:39 UTC, adisuciu commented on src/contextbuilder.cpp
> +		if (deinit && !ctx_impl->getContextOwnership())
Can this be translated to
if(deinit) 
  device->deinitialize() 
?

2023-12-07 08:43 UTC, AlexandraTrifan approved these changes

2024-01-29 09:40 UTC, adisuciu approved these changes

2024-01-29 12:36 UTC, merged