Review LGPL-2.1 license headers
analogdevicesinc/libm2k pull request #371
Opened 2024-09-19 15:08 UTC by Adrian-Stanea

## Introduction 
This PR standardizes the license headers and fixes version mismatches, ensuring all files use `LGPL v2.1` instead of `v2` or `v3`.

## To be discussed
1. These files are currently under the more restrictive ADI-BSD license. They should be reviewed to either replace them with alternatives under a more permissive license or to ensure proper mention of their license in the documentation or project files.
    - [ ] include/libm2k/tools/i2c.hpp
    - [ ] include/libm2k/tools/spi.hpp
    - [ ] include/libm2k/tools/uart.hpp
2. Consider adding a CI check to ensure that certain files contain the appropriate license headers. The CI check should fail if any files do not follow the established license guidelines.

## Note

The following files and directories have been omitted from the reviewed files:
### Directories:
  - `.git*`
  - `build`
  - `CI`
  - `img`
  - `results`
 
### Files:
  - `.gitignore`
  - `*.png`
  - `*.rst`
  - `53-adi-m2k-usb.rules`
  - `AssemblyInfo.cs.in`
  - `azure-pipelines.yml`
  - `Doxyfile_API.in`

2024-09-20 06:16 UTC, AlexandraTrifan commented on bindings/labview/libm2k_lv.cpp
> +#include <libm2k/contextbuilder.hppbindings/libm2k.i>
i think this is a unwanted change

2024-09-20 06:30 UTC, AlexandraTrifan approved these changes
Otherwise looks good. 
Let's wait for @adisuciu to take a look at this also.
And for now we'll keep this PR open until we have a clear overview of the tools/i2c spi and uart files you mentioned earlier.

It would indeed be a good idea to add a CI job to run a script and do a minimal checkup of the license header existence and version.

2024-09-20 06:32 UTC, AlexandraTrifan requested changes
later edit: We should not modify the license headers in files from deps/wingetopt

2024-09-23 08:34 UTC, Adrian-Stanea commented on bindings/labview/libm2k_lv.cpp
> +#include <libm2k/contextbuilder.hppbindings/libm2k.i>
Removed

2024-09-23 08:41 UTC, Adrian-Stanea commented
> later edit: We should not modify the license headers in files from deps/wingetopt

Removed license header from cmake file from tools/deps/wingetopt

2024-10-01 13:03 UTC, Adrian-Stanea commented
Replaced ADI-BSD license

2024-10-09 10:06 UTC, AlexandraTrifan approved these changes

2024-10-09 10:06 UTC, merged